name: curso-ciencia-datos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.4
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - plotly=5.14.1
  - pyspark=3.4.1
  - jupyterlab=4.0.5
  - ipywidgets=8.0.7
  - notebook=7.0.0
  - statsmodels=0.14.0
  - scipy=1.10.1
  - openpyxl=3.1.2
  - xlrd=2.0.1
  - pip:
      - missingno==0.5.2
      - pyarrow==12.0.1
